#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

CONTROLLER="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/prepare-paralon-world.sh"
ENV_FILE="$HOME/regnum/paralon-prep/wizard.env"
mkdir -p "$(dirname "$ENV_FILE")"
[[ -x "$CONTROLLER" ]] || { printf 'missing controller: %s\n' "$CONTROLLER" >&2; exit 1; }

banner "Regnum Paralon world preparation"

stage "Identify the authorized map"
say "Extract the authorized Paralon world on Hermes beneath ~/regnum/incoming."
step "Enter the directory that directly contains level.dat and region/."
ask PARALON_WORLD "Paralon world directory:"
ask PARALON_EDITION "Exact Paralon edition or release name:"
[[ -n "$PARALON_WORLD" && -n "$PARALON_EDITION" ]] || { warn "both values are required"; exit 1; }
write_env PARALON_WORLD "$PARALON_WORLD"
write_env PARALON_EDITION "$PARALON_EDITION"
metrics=$("$CONTROLLER" inspect "$PARALON_WORLD")
printf '%s\n' "$metrics"

while IFS='=' read -r key value; do
  case "$key" in
    RECOMMENDED_CENTER_X) RECOMMENDED_CENTER_X="$value" ;;
    RECOMMENDED_CENTER_Z) RECOMMENDED_CENTER_Z="$value" ;;
    MIN_RADIUS_CHUNKS) MIN_RADIUS_CHUNKS="$value" ;;
    APPROX_CIRCLE_CHUNKS) APPROX_CIRCLE_CHUNKS="$value" ;;
    ALLOCATED_CHUNKS) ALLOCATED_CHUNKS="$value" ;;
  esac
done <<<"$metrics"
[[ -n "${MIN_RADIUS_CHUNKS:-}" ]] || { warn "map inspection returned no radius"; exit 1; }

stage "Confirm the real map boundary"
say "The radius comes from the imported region files. It does not use the old 625-chunk claim or a DH render radius."
note "Detected center: ${RECOMMENDED_CENTER_X}, ${RECOMMENDED_CENTER_Z}"
note "Minimum covering radius: ${MIN_RADIUS_CHUNKS} chunks"
note "Chunks already stored in the map: ${ALLOCATED_CHUNKS}"
note "Approximate circular workload: ${APPROX_CIRCLE_CHUNKS} chunks"
[[ -n "$(_existing PARALON_CENTER_X || true)" ]] || write_env PARALON_CENTER_X "$RECOMMENDED_CENTER_X"
[[ -n "$(_existing PARALON_CENTER_Z || true)" ]] || write_env PARALON_CENTER_Z "$RECOMMENDED_CENTER_Z"
[[ -n "$(_existing PARALON_RADIUS_CHUNKS || true)" ]] || write_env PARALON_RADIUS_CHUNKS "$MIN_RADIUS_CHUNKS"
ask PARALON_CENTER_X "Chunky and DH center X:"
ask PARALON_CENTER_Z "Chunky and DH center Z:"
ask PARALON_RADIUS_CHUNKS "Shared radius in chunks:"
[[ "$PARALON_CENTER_X" =~ ^-?[0-9]+$ && "$PARALON_CENTER_Z" =~ ^-?[0-9]+$ && "$PARALON_RADIUS_CHUNKS" =~ ^[0-9]+$ ]] ||
  { warn "center and radius must be integers"; exit 1; }
(( PARALON_RADIUS_CHUNKS >= MIN_RADIUS_CHUNKS )) || { warn "radius does not cover every imported region"; exit 1; }
write_env PARALON_CENTER_X "$PARALON_CENTER_X"
write_env PARALON_CENTER_Z "$PARALON_CENTER_Z"
write_env PARALON_RADIUS_CHUNKS "$PARALON_RADIUS_CHUNKS"

stage "Back up and install Paralon"
say "The controller keeps a compressed backup and a rollback directory. It never deletes the current world."
say "Existing mature Paralon trees remain vanilla. New placed saplings use Dynamic Trees."
ask PARALON_PLAYER_MODE "Player data mode, reset or preserve:"
[[ "$PARALON_PLAYER_MODE" == reset || "$PARALON_PLAYER_MODE" == preserve ]] ||
  { warn "player data mode must be reset or preserve"; exit 1; }
write_env PARALON_PLAYER_MODE "$PARALON_PLAYER_MODE"
warn "This stage stops Regnum and replaces ~/regnum/new-server/mc/world."
confirm "Install the inspected Paralon copy now?" || { warn "cancelled before world replacement"; exit 0; }
PARALON_CONFIRM="REPLACE CURRENT REGNUM WORLD" "$CONTROLLER" install \
  "$PARALON_WORLD" "$PARALON_EDITION" "$PARALON_PLAYER_MODE" \
  "$PARALON_CENTER_X" "$PARALON_CENTER_Z" "$PARALON_RADIUS_CHUNKS"

stage "Load and fill real chunks with Chunky"
say "The controller disables DH generation before Chunky starts and forces existing premade chunks to load."
warn "This can run for days on a 50K map. Keep this wizard inside tmux."
confirm "Start or resume the guarded Chunky phase?" || { warn "Chunky not started"; exit 0; }
"$CONTROLLER" chunky-start
"$CONTROLLER" chunky-wait

stage "Build Distant Horizons LODs"
say "Only after a verified Chunky completion does the controller re-enable DH and use the same center and chunk radius."
confirm "Start or resume the guarded DH pregeneration phase?" || { warn "DH pregeneration not started"; exit 0; }
"$CONTROLLER" dh-start
"$CONTROLLER" dh-wait

stage "Return Regnum to its safe idle state"
"$CONTROLLER" finalize
"$CONTROLLER" status
SKIPPED+=("Connect a real client and inspect Paralon's outer edge and several interior LOD regions before opening the server to players")

finish
